[package]
name = "quant"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.16.1"
imagequant = { version = "4", default-features = false }
wasm-bindgen = "0.2.92"
